# need sudo for docker
sudo: required

language: node_js

# skip install step (npm install)
# See http://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

services:
  - docker

script:
  - docker run influxteam/node-influx:v1
